### ISSUE TITLE
CodeGeneration

### ISSUE THREAD

**Issue by Lelantus** [Sileken/C0-Compiler#12]
Issue to comment on code generation.

List of ToDo's / Done's

- [x] VariableDeclarationExpression (should nothing be done)

- [x] VariableDeclaration

- [x] Name

- [x] LiteralPrimary (how to handle NULL?)

- [x] AssignmentExpression 

- [x] UnaryExpression (need test dereference, is !false in CMa -(0/1)?)

- [x] BinaryExpression (needs more testing )

- [x] MethodInvokeExpression

- [x] ReturnStatement

- [x] IfStatement

- [x] WhileStatement

- [x] ForStatement

- [x] AllocExpression

- [x] ArrayAccess

- [x] FieldAccess 

- [x] FieldDereferenceAccess

So everybody can write his name behind the function

**Comment by Lelantus** [comment]
The current placement of the .cma output file ist in _compiler/bin_

The output file will be successfully processed by the current CMA implementation!
(But currently there are no operations implemented^^)

**Comment by Sileken** [comment]
Done
