### ISSUE TITLE
Skip Zeichen incl. linecount

### ISSUE THREAD

**Issue by Lelantus** [Sileken/C0-Compiler#2]
Einbauen der SKIP-Zeichen incl. Counter für die Zeilen

**Comment by Lelantus** [comment]
Hat jemand noch das Beispiel für das Zählen der Zeilen? War das vielleicht in der Übung und nicht mehr auf den Videos drauf?

**Comment by Sileken** [comment]
Ich habe es auch nicht mehr.

**Comment by Lelantus** [comment]
Beispieldatei ist: "Blocks.jj" direkt im elearning unter Symboltabelle.

Schaue es mir demnächst nochmal genauer an.

**Comment by Sileken** [comment]
Wird von der Token Klasse schon gemacht
