### ISSUE TITLE
Grammar implementation in javacc

### ISSUE THREAD

**Issue by Sileken** [Sileken/C0-Compiler#5]
Almost finished.
Currently tasks are:

- Removing warnings
- Removing global lookahead
- Improving expression production

**Comment by Twanks1** [comment]
Expression() BinaryOp() Expression() makes problem with the current grammar
e.g. a[0] = a[1] + 3

**Comment by Lelantus** [comment]
Changed expression implementation; now "struct->arr[5]" works, but "a[0] = a[1] + 3--" doesn't.

In the C0 grammar-specification postOp is used only in combination with Lv, so it should not work within an expression?

**Comment by Twanks1** [comment]
No warnings and everything works so far. This might be finished, unless there is something missing.

**Comment by Sileken** [comment]
Start refactoring simple() and lv() production.

**Comment by Sileken** [comment]
Expression() == Expression() makes problem with the current grammar.

**Comment by Twanks1** [comment]
grammar should work now :-)

**Comment by Sileken** [comment]
Done
