### ISSUE TITLE
Implementing the syntax tree

### ISSUE THREAD

**Issue by Sileken** [Sileken/C0-Compiler#6]
- Creating syntax tree node classes
- Extend grammar production to create syntax tree nodes.

**Comment by Sileken** [comment]
The simple syntax tree for the following production should be done:
- <prog>
- <gdecl>
- <gdefn>
- <tp>

The simple syntax tree is for the following production are still missing:
- <stmt>
- <simple>
- <lv>
- <exp>

**Comment by Sileken** [comment]
Startet with AST for stmt.

**Comment by Twanks1** [comment]
Same AST for different statements:
  as->q[0];
  as[0];

**Comment by Sileken** [comment]
Done
