### ISSUE TITLE
Implementing SymbolTable

### ISSUE THREAD

**Issue by Lelantus** [Sileken/C0-Compiler#9]
Going to re-view the video about symbol table.
Creating concept and basis-classes.

**Comment by Lelantus** [comment]
Last commit is just a first design of the symboltable as data structure.

Further required: traversing of the AST and creating the structure/symboltable.

**Comment by Lelantus** [comment]
Last commit is a first example of traversing the AST and creating the symbol table.

Further required: appending the information of symbols to the ASTNodes 
 * declarationNode

- Still a problem: scopes of different functions can lookup any identifier

**Comment by Twanks1** [comment]
See new issue about the new symboltable
